### ISSUE TITLE
Clearer documentation

### ISSUE THREAD

**Issue by focusaurus** [hemanth/greener#11]
It's unclear to me based on the README what this module does. From running it, it looks to enumerate all your public github node projects and enable them all for greenkeeper. The current documentation led me to believe this was actually going to directly tell me about dependency updates.

**Comment by hemanth** [comment]
Agree, would you like to rephrase it?

**Comment by focusaurus** [comment]
How about "Enables greenkeeper integration for all your public github repositories"?

**Comment by hemanth** [comment]
Done, thanks.
